### ISSUE TITLE
clarification(?)

### ISSUE THREAD

**Issue by Moscarda** [w0lfschild/binventory_SIMBL#1]
I see there are no items here, but from your description, it sounds like something I've been looking into:  trying to create a tool which can be used to "theme" the dock by programmatically substituting a set of icons for the normal app icons (to avoid the need to edit the package contents, which can break many apps) and also having a difference badged icon for when an app is opened, like have it change color.

**Comment by w0lfschild** [comment]
This is actually going to be a fork of https://github.com/ParasiteTeam/extensions/tree/master/binventory

With support for SIMBL and ideally a fix so it loads without the trash state changing (which is what I'm having problems with).

**Comment by w0lfschild** [comment]
I figured it out and a release is out now.
