### ISSUE TITLE
Violates License of Original Source

### ISSUE THREAD

**Issue by alexzielenski** [w0lfschild/binventory_SIMBL#2]
Hi,

It's pretty clear from the copyright notices in the code and the retention of the name of the original product that the source of this code is here: https://github.com/ParasiteTeam/extensions/. However, it seems like you completely ignored my license and opted to only obey the license of SGDirWatchDog.

I was a bit taken aback by the creation of this repository because the changes made are too minimal to skirt over the fact that 99.9% of what is presented is not yours which I feel is unclassy.

You are welcome to retain the repository since I imagine some people may want this product for SIMBL, I ask that you include the license file from the original repo in both the source and binary distributions of the product and be a little more clear in the README about the original source of the code, seeing as you neglected to not fork it, excluding any references to the parent repository. Please be more careful in the future to avoid copyright infringement and plagiarism.

Thanks.

**Comment by w0lfschild** [comment]
Done.
